# Model parameters
acupoint_definitions_path: "path/to/acupoint_definitions.json"
num_acupoints: 84
smpl_model_path: "path/to/smpl_model.pkl"
skel_model_path: "path/to/skel_model.pkl"
pretrained_vit_path: "path/to/vit_pretrained.pth"
device: "cuda"

# Training parameters
seed: 42
exp_name: "acupoint_prediction"
output_dir: "outputs/acupoint"

# Data parameters
train:
  image_paths: "path/to/train/images"
  keypoint_paths: "path/to/train/keypoints"
  acupoint_paths: "path/to/train/acupoints"
  batch_size: 32
  num_workers: 4

val:
  image_paths: "path/to/val/images"
  keypoint_paths: "path/to/val/keypoints"
  acupoint_paths: "path/to/val/acupoints"
  batch_size: 32
  num_workers: 4

# Augmentation parameters
augmentation:
  occlusion_prob: 0.3
  max_occlusion_size: 0.2
  pose_perturb_std: 0.1

# Trainer parameters
trainer:
  devices: 1
  max_epochs: 100
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  precision: 16
  amp_backend: "native"

# Loss weights
loss_weights:
  acupoint_2d: 0.1  # Will be dynamically adjusted
  keypoint_2d: 1.0
  shape_prior: 0.1
  pose_prior: 0.1
  skeleton_consistency: 0.1

# Optimization parameters
optimizer:
  type: "Adam"
  lr: 0.0001
  weight_decay: 0.0001

# Learning rate scheduler
scheduler:
  type: "CosineAnnealingLR"
  T_max: 100
  eta_min: 0.00001 